"""Add face_verified column to users

Revision ID: 5dd0f3625445
Revises: 7a75bc628588
Create Date: 2025-04-18 11:37:22.482299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd0f3625445'
down_revision: Union[str, None] = '7a75bc628588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_verified')
    # ### end Alembic commands ###
