"""added face embeddings

Revision ID: 7a75bc628588
Revises: faabf5f10ff1
Create Date: 2025-04-18 01:39:10.080135

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector import sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '7a75bc628588'
down_revision: Union[str, None] = 'faabf5f10ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable the vector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sqlalchemy.vector.VECTOR(dim=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector;")
