"""fk constraints changes

Revision ID: cdc697acb497
Revises: e291f22949de
Create Date: 2025-04-28 16:13:50.493315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc697acb497'
down_revision: Union[str, None] = 'e291f22949de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_event_id_fkey', 'attendance', type_='foreignkey')
    op.drop_constraint('attendance_user_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('face_embeddings_user_id_fkey', 'face_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'face_embeddings', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'face_embeddings', type_='foreignkey')
    op.create_foreign_key('face_embeddings_user_id_fkey', 'face_embeddings', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_user_id_fkey', 'attendance', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('attendance_event_id_fkey', 'attendance', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###
